### PR TITLE
Add Laravel 8 support

### PR DESCRIPTION
**Pull request by agentphoenix**
This PR adds support for today's release of Laravel 8.

One note about this PR: Laravel 8 bumps the PHP requirement to PHP 7.3 (reflected in the updates). I'm not sure what you want to do about versioning for a change like this, but thought I'd call it out specifically.

### CODE REVIEW

**Comment by BSN4** [comment]
thanks but php should be at least php 7.2

**Comment by abdumu** [comment]
> thanks but php should be at least php 7.2 

I agree since we are supporting older Laravel versions

**Comment by agentphoenix** [comment]
@if4lcon Reverted back to the previous requirements

**Comment by BSN4** [comment]
thank you so much

**Comment by agentphoenix** [comment]
@if4lcon Glad to help! Do you have an idea of when you're going to tag the release? Just waiting on this package to do my Laravel 8 upgrade. Thanks for the great package!

**Comment by BSN4** [comment]
Done 👍

**Pull request merged**
